name: expression_parser
description: Evaluate Mathematical Expressions
version: 1.0.0
repository: https://github.com/EsinShadrach/expression_parser
environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
